<table align="center" width=100%>
    <tr>
        <td width="20%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Inclass - Lab <br>(Week 4)
                    </b>
                </font>
            </div>
        </td>
        <td width="25%">
            <img src="GL-2.png">
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1d)**
2. **[Two Dimensional Array](#2d)**

**Import the NumPy library before solving the exercises**

In [2]:
import numpy as np

### Let's begin with some hands-on practice exercises

<a id="1d"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [10]:
# type your code here
list_temperature = np.array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68], dtype=np.float16)
print(list_temperature, type(list_temperature))

[3.04 1.65 5.76 1.66 1.54 4.69 2.68] <class 'numpy.ndarray'>


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [8]:
weights = np.array([74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82])
index = weights>68
print(weights[index])


[74.2 85.  74.  70.5 86.  82. ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Explanation:** It is possible to generate same random numbers everytime. There is a function called, random.seed() in numpy which gives the same random numbers everytime. It is necessary to set the random seed just before generating the random numbers to get the same values

In [7]:
np.random.seed(0)
x = np.random.randint(20, 40, 10)
x

array([32, 35, 20, 23, 23, 27, 29, 39, 38, 24])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [14]:
x = np.linspace(1, 5, 5)
np.power(x, 5)

array([1.000e+00, 3.200e+01, 2.430e+02, 1.024e+03, 3.125e+03])

In [18]:
a=np.random.randint(1,6, 5)
np.power(np.arange(1, 6), 5)

array([   1,   32,  243, 1024, 3125])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [20]:
def odd_array(start, stop):
    x = np.arange(start, stop)
    return x[x%2!=0]

odd_array(50, 100)

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [23]:
A =np.array( [[1, 4, 8], [5, 7, 3], [9, 14, 2]])
A # axis = 0, 1
np.sum(A, axis=1)

array([13, 15, 25])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [24]:
num = np.array([42, 87, 90, 14, 32, 75, 61, 80, 92]) % 8
num

array([2, 7, 2, 6, 0, 3, 5, 0, 4])

<a id="2d"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [30]:
a = np.arange(1, 21)
a = a.reshape(4, 5)
a[1]

array([ 6,  7,  8,  9, 10])

In [25]:
# type your code here
a = np.arange(1, 21)
b = a.reshape(4, 5)
print(b)
subset = b[1, :]
print(subset)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6  7  8  9 10]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [26]:
prices_monday = np.array([10, 30, 50, 60, 90])

prices_tuesday = np.array([50, 20, 80, 125, 10, 70])

np.intersect1d(prices_monday, prices_tuesday)

array([10, 50])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

In [27]:
# bmi formula = weight / height^2
weights = np.array([57, 69, 54, 65 ,71, 62, 56])
heights = np.array([1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53])

bmi = weights / np.power(heights, 2)
print(bmi)

[22.54657648 22.53061224 19.59645812 21.46915048 26.39797739 20.9572742
 23.922423  ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [31]:
# type your code here
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a program to transpose a matrix
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [32]:
M = np.array([[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]])
M

array([[15, 17, 45, 56],
       [ 7, 42, 15, 63],
       [54,  3, 61, 41],
       [ 0, 87, 16, 20]])

In [33]:
M.transpose()

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

In [ ]:
# home work: find the difference between reshare and transpose and see now the elements are aligned 

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [ ]:
# type your code here